version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=https://supabase.com/dashboard/project/rmqpfqtcbzmylxmppehi
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcXBmcXRjYnpteWx4bXBwZWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDAzNDcsImV4cCI6MjA2OTA3NjM0N30.LfYwttVguSZIu4ypj5U_UP8vNo6FbbcElXmUy_b0IXU

volumes:
  pgdata:
